global:
  namespace: default
  project: default
  server: https://kubernetes.default.svc
  repo:
    url: https://github.com/vladimir-babichev/gitops-argocd/
    revision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

applications:
# applications:
#   vault:
#     path: k8s/core/vault
#   argocd:
#     path: k8s/core/argocd
#     plugin:
#       name: argocd-vault-plugin-helm
#       env:
#         - name: helm_args
#           value: -f values-dev.yaml

appProjects:
# appProjects:
#   gitops:
#     annotations:
#       argocd.argoproj.io/sync-wave: "-10"
#     destinations:
#       - namespace: gitops
#         server: https://kubernetes.default.svc
#     clusterResourceWhitelist:
#       - group: "*"
#         kind: "*"
#     sourceRepos:
#       - "*"
